@startuml

title __EXCEPTION's Package Diagram__\n

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.exception {
      class NoItemsAvailableException {
          + NoItemsAvailableException()
      }
    }
  }
  

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.exception {
      class NoValueInputException {
          + NoValueInputException()
      }
    }
  }

@enduml
