package com.shneddy.dietdiary.exception;
/**
 * Created By Seth Sneddon Mar 2019
 */
public class NoItemsAvailableException extends Exception {

    /**
     * Utilized to create pop up messages when exceptions are generated by the user
     * @param message that will be passed to pop-up
     */
    public NoItemsAvailableException(String message){
        super(message);
    }

}
