@startuml

title __DAO's Package Diagram__\n

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.dao {
      interface DiaryEntryDAO {
          {abstract} + insert()
          {abstract} + update()
          {abstract} + delete()
          {abstract} + deleteAllFoodTypes()
          {abstract} + getAllDiaryEntries()
          {abstract} + getAllEntriesList()
          {abstract} + getAllEntriesListByDiemId()
          {abstract} + getEntriesByDiemId()
      }
    }
  }
  

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.dao {
      interface DiemDAO {
          {abstract} + insert()
          {abstract} + update()
          {abstract} + delete()
          {abstract} + getByDateString()
          {abstract} + joinGetById()
          {abstract} + getLiveDataDiem()
          {abstract} + getJoinedTables()
      }
    }
  }
  

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.dao {
      interface DiemEntryFoodDAO {
          {abstract} + getByDiemId()
      }
    }
  }
  

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.dao {
      interface FoodAndEntryDAO {
          {abstract} + getFoodAndEntryList()
          {abstract} + getFoodAndEntryById()
      }
    }
  }
  

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.dao {
      interface FoodDAO {
          {static} + foodtype : FoodType
          {abstract} + insert()
          {abstract} + update()
          {abstract} + delete()
          {abstract} + deleteAllFoods()
          {abstract} + getAllFoods()
          {abstract} + getAllFoodsList()
          {abstract} + getFoodById()
          {abstract} + search()
          {abstract} + searchString()
      }
    }
  }
  

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.dao {
      interface FoodTypeDAO {
          {abstract} + insert()
          {abstract} + update()
          {abstract} + delete()
          {abstract} + deleteAllFoodTypes()
          {abstract} + getAllFoodTypes()
          {abstract} + getAllFoodTypesList()
      }
    }
  }
  

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.dao {
      interface TypeAndFoodDAO {
          {abstract} + getTypeAndFoodsList()
          {abstract} + getFoodAndTypeById()
      }
    }
  }

@enduml
