@startuml

title __DATABASE's Package Diagram__\n

  package com.shneddy.dietdiary {
    package com.shneddy.dietdiary.database {
      abstract class FoodDiaryDatabase {
          {static} - instance : FoodDiaryDatabase
          {abstract} + foodDAO()
          {abstract} + entryDAO()
          {abstract} + foodTypeDAO()
          {abstract} + typeAndFoodDAO()
          {abstract} + foodAndEntryDAO()
          {abstract} + diemDAO()
          {static} + getInstance()
      }
    }
  }
  

  FoodDiaryDatabase -up-|> RoomDatabase

@enduml
